# Generated by Django 3.2.12 on 2022-02-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalist_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speech', models.TextField(max_length=100000)),
            ],
        ),
    ]
